// <auto-generated />
using System;
using Kutuphane.Data.EntityFramework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Kutuphane.Data.Migrations
{
    [DbContext(typeof(KutuphaneDBContext))]
    partial class KutuphaneDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Kutuphane.Data.Entities.tblKitapHareketler", b =>
                {
                    b.Property<int>("KitapHareketID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Ad")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<DateTime?>("BaslangicTarihi")
                        .HasColumnType("DATETIME");

                    b.Property<DateTime?>("BitisTarihi")
                        .HasColumnType("DATETIME");

                    b.Property<byte?>("Durum")
                        .HasColumnType("TINYINT");

                    b.Property<string>("EPosta")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal>("GunlukCezaTutari")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("DECIMAL(18,2)")
                        .HasDefaultValue(5m);

                    b.Property<int?>("KitapID_FK")
                        .HasColumnType("int");

                    b.Property<string>("Soyad")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<long?>("TCNo")
                        .HasColumnType("BIGINT");

                    b.Property<string>("Telefon")
                        .HasColumnType("VARCHAR(12)");

                    b.Property<DateTime?>("TeslimTarihi")
                        .HasColumnType("DATETIME");

                    b.Property<decimal?>("ToplamCezaTutari")
                        .HasColumnType("DECIMAL(18,2)");

                    b.HasKey("KitapHareketID");

                    b.HasIndex("KitapID_FK");

                    b.ToTable("tblKitapHareketler");
                });

            modelBuilder.Entity("Kutuphane.Data.Entities.tblKitaplar", b =>
                {
                    b.Property<int>("KitapID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Baslik")
                        .HasColumnType("VARCHAR(255)");

                    b.Property<byte?>("Durum")
                        .HasColumnType("TINYINT");

                    b.Property<string>("ISBN")
                        .HasColumnType("VARCHAR(50)");

                    b.Property<decimal?>("KapakFiyati")
                        .HasColumnType("DECIMAL(18,2)");

                    b.Property<int>("YayinYili")
                        .HasColumnType("INT");

                    b.HasKey("KitapID");

                    b.ToTable("tblKitaplar");
                });

            modelBuilder.Entity("Kutuphane.Data.Entities.tblKitapHareketler", b =>
                {
                    b.HasOne("Kutuphane.Data.Entities.tblKitaplar", "KEY_KitapID_FK")
                        .WithMany("LIST_tblKitapHareketler_KitapID_FK")
                        .HasForeignKey("KitapID_FK")
                        .HasConstraintName("FK_tblKitapHareketler_KitapID_FK");

                    b.Navigation("KEY_KitapID_FK");
                });

            modelBuilder.Entity("Kutuphane.Data.Entities.tblKitaplar", b =>
                {
                    b.Navigation("LIST_tblKitapHareketler_KitapID_FK");
                });
#pragma warning restore 612, 618
        }
    }
}
